# Generated by Django 3.0.5 on 2020-05-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='frequencyofRecurrence',
            field=models.CharField(choices=[('Breakfast, Mon', 'B1'), ('Breakfast, Mon-Tue', 'B2'), ('Breakfast, Mon-Wed', 'B3'), ('Breakfast, Mon-Thur', 'B4'), ('Breakfast, Mon-Fri', 'B5'), ('Lunch, Mon', 'L1'), ('Lunch, Mon-Tue', 'L2'), ('Lunch, Mon-Wed', 'L3'), ('Lunch, Mon-Thur', 'L4'), ('Lunch, Mon-Fri', 'L5'), ('ONCE', 'ONCE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='menu',
            name='isRecurring',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=10),
        ),
    ]
