# Generated by Django 3.0.5 on 2020-05-26 10:59

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20200525_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.Menu')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='amountDue',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amountOutstanding',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amountPaid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customerId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dateTimeOfOrder',
        ),
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='itemsOrdered',
        ),
        migrations.AddField(
            model_name='order',
            name='totalamount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Placed', 'Placed'), ('Acknowledged', 'Acknowledged'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Dispatched', 'Dispatched')], default='Waiting', max_length=50),
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ord_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.Order'),
        ),
    ]
